### ISSUE TITLE
インテリセンスでexception

### ISSUE THREAD

**Issue by hrtk91** [Y-Koji/CsTxt#2]
https://github.com/Y-Koji/CsTxt/blob/f1bb8ab2863e556dfc5d59b13d032d420f137d86/CSTPad/Model/Text/IntellisencePopupProcessor.cs#L24-L30

for (int i = 0; i < 10; i++)
                                 ^
上記のコードでi++がRegexの量指定演算子が多いとして例外出ます。
word = Regex.Escaped(word);だとだめ？

**Comment by Y-Koji** [comment]
そのメソッドに気が付かなかった．．．
そっちがいいっすね

**Comment by Y-Koji** [comment]
6210c285274bdbcaa17721dbdcd6f06eac3e9d65 で対応～

**Comment by Y-Koji** [comment]
924caea8845e83abd0c7d2371e704e08e1fa1266 でした．
